### ISSUE TITLE
link error in DrRacket

### ISSUE THREAD

**Issue by dougo** [dyoo/whalesong#19] opened 2011-09-06 01:10 UTC
This module works fine from the command line (well, it prints 'not-done-yet) and can be built and viewed in a browser:

```
#lang planet dyoo/whalesong

(require (planet dyoo/whalesong/js))

(call-method ($ "<h1>Hello World</h1>")
             "appendTo"
             body)

(void)
```

But when I try to Check Syntax or Run in DrRacket, I get this error:

```
index.rkt:5:1: link: module mismatch, probably from old bytecode whose dependencies have changed: variable not provided (directly or indirectly) from module: "/home/dougo/whalesong/js/main.rkt" accessed from module: 'index at source phase level: 0 in: call-method
```

Not sure if this is a problem with Whalesong or DrRacket or some installation problem.  I'm running 5.1.3--2011-08-16(-/f).

**Comment by dyoo** [comment] 2011-09-06 01:23
On Mon, Sep 5, 2011 at 9:10 PM, dougo <reply+i-1574426-

>    index.rkt:5:1: link: module mismatch, probably from old bytecode whose dependencies have changed: variable not provided (directly or indirectly) from module: "/home/dougo/whalesong/js/main.rkt" accessed from module: 'index at source phase level: 0 in: call-method

Yeah, this is https://github.com/dyoo/whalesong/issues/15 and I
haven't quite figured out how to play nice with DrRacket's debugging
annotations.  I haven't figured out yet why this is happening.
Closing this issue because it's a duplicate of 15.

**Closed as completed** 2011-09-06 01:23 UTC
